name: Build AnnoyingMarkdown

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:  [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            output: out/annoyingmarkdown_linux
            build: build.sh

          - os: windows-latest
            output: out/annoyingmarkdown_windows.exe
            build: build.sh

          - os: macos-latest
            output: out/annoyingmarkdown_macos
            build: build.sh
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: development

#      - if: matrix.os == 'ubuntu-latest'
#        name: Update linux packages
#        run: | 
#          sudo apt update 
#          sudo apt upgrade

      - name: Permissions
        run: |
          chmod +x ${{ matrix.build }}

      - name: Build
        run: ./${{ matrix.build }}

      - name: Test
        run: ./${{ matrix.output }} Hello World

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: AnnoyingMarkdown
          path: ./${{ matrix.output }}
